CREATE TABLE IF NOT EXISTS leads_libras (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NULL,
  email VARCHAR(180) NULL,
  telefone VARCHAR(40) NULL,
  origem VARCHAR(60) NOT NULL DEFAULT 'site',
  mensagem TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (email),
  INDEX (telefone),
  INDEX (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
