jobs:
name: build-and-deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Prepare backend dist
        run: |
          rm -rf backend/dist || true
          mkdir -p backend/dist
          cp -r frontend/dist/* backend/dist/
          if [ -f backend/.htaccess ]; then cp backend/.htaccess backend/dist/.htaccess; fi
          ls -la backend/dist || true

      - name: Install lftp (for robust FTP mirror)
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload to Plesk via FTP (lftp mirror)
        env:
          FTP_HOST: 168.75.84.128
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASS: ${{ secrets.FTP_PASSWORD }}
          REMOTE_DIR: /httpdocs/backend
        run: |
          echo "Starting lftp upload to $FTP_HOST (remote: $REMOTE_DIR)"
          # Show connection test (will fail fast with clear output if credentials/wrong host)
          lftp -u "$FTP_USER","$FTP_PASS" -e "set ftp:passive-mode on; set ssl:verify-certificate no; pwd; ls -la; quit" ftp://$FTP_HOST || true
          # Mirror local -> remote, delete extraneous files on remote, preserve permissions where possible
          lftp -u "$FTP_USER","$FTP_PASS" ftp://$FTP_HOST -e "set ftp:passive-mode on; set net:max-retries 2; set net:timeout 20; mirror -R --verbose --delete --parallel=2 backend/dist $REMOTE_DIR; quit"

      - name: Optional: Configure SSH & rsync (fallback)
        if: ${{ secrets.PLESK_SSH_KEY != '' && secrets.PLESK_SSH_USER != '' && secrets.PLESK_SSH_HOST != '' && secrets.PLESK_TARGET_DIR != '' }}
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PLESK_SSH_KEY }}

      - name: Optional: Fallback upload via rsync over SSH
        if: ${{ secrets.PLESK_SSH_KEY != '' && secrets.PLESK_SSH_USER != '' && secrets.PLESK_SSH_HOST != '' && secrets.PLESK_TARGET_DIR != '' }}
        run: |
          rsync -avz --delete backend/dist/ ${{ secrets.PLESK_SSH_USER }}@${{ secrets.PLESK_SSH_HOST }}:${{ secrets.PLESK_TARGET_DIR }}
